### ISSUE TITLE
Map search not working as expected

### ISSUE THREAD

**Issue by fosterlynn** [Carbon-Farm-Network/app-carbon-farm-network#24]
Or working with strange rules, see below.

![Screenshot from 2023-07-20 09-03-54](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/a62f6d00-6341-4050-8a29-fef255efe1f4)

**Comment by pospi** [comment]
fixed in 369458c

**Comment by fosterlynn** [comment]
Reopening.  Still not working for me.  It seems like it should have, but I'm not positive that this commit made it into the release that came out yesterday afternoon?
![Screenshot from 2023-08-02 12-11-17](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/ca3a8a2f-b708-4322-a3d2-2b02865eb2e7)

Oddly, it is still bringing up a subset of the agents.  Is there a limit to how many it will show?

**Comment by fosterlynn** [comment]
Testing again with new release, here are some results.  It is doing something, but unclear to me what.  Below the search screen prints are the popup prints so you can see the data.  If you need to see more data, the seed is acfn-8-11.
![Screenshot from 2023-08-12 12-29-50](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/94b5e44d-fa26-4e32-a1d7-05899a6298d4)
![Screenshot from 2023-08-12 12-30-04](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/71e0c1c7-907d-42b3-981b-fe9227f17f02)
![Screenshot from 2023-08-12 12-30-55](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/904a91a4-ad2f-4c9a-9024-59f66e091be1)
![Screenshot from 2023-08-12 12-31-16](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/d0578ca5-f21b-415d-8fb8-59af909adafb)
![Screenshot from 2023-08-12 12-31-30](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/3405f1cb-a7d6-4d5a-80e3-8a040606f1b9)
![Screenshot from 2023-08-12 12-31-50](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/3fac3579-15f7-43e5-a366-16ee38a5fab5)
![Screenshot from 2023-08-12 12-45-43](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/b4d35bec-ca8b-474c-a753-2f092510fb0d)
![Screenshot from 2023-08-12 12-45-48](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/272c9a6a-c33f-4624-ad06-b5c110b464ed)
![Screenshot from 2023-08-12 12-45-52](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/2c97eb76-1369-4972-adf0-65e749164ce4)

**Comment by fosterlynn** [comment]
Possible additional clues, at least to try to re-create:  

When I first went into the map on my new installation, after entering a couple agents, and typed "scour" into the search, it correctly brought up only the agent with "scour" in it's information.  From then on, it always brought up both agents no matter what I entered.  Even going out and back into the app itself now it always brings up both agents.

I think also after I had the one successful search, I entered facets and an offer for one agent.

**Comment by pospi** [comment]
Should be fixed in latest commits, was an issue with recursively matching against agents involved deeper in the Proposal data attached to Agents for the purposes of display on the map.

**Comment by fosterlynn** [comment]
Sorry, re-opening again, not working for me, although it is different.  I'll ask Laura/Evan to test this too.

![Screenshot from 2023-09-19 07-02-50](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/c6643326-6cfa-459d-8c9d-68a88074bb12)

![Screenshot from 2023-09-19 06-57-15](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/7d9b6306-950f-448d-8dfa-5dab0421c257)

But.... (probably from the "valley" part, with more of "alpaca" it disappeared)
![Screenshot from 2023-09-19 06-57-01](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/assets/3776081/3b1d2bea-e1f7-496e-b209-42def2f6e4f7)

If you want to test, feel free to join seed acfn-09-19, but let me know so I can bring it up first.
